version: '2'
services:
  db: 
    image: mongo
    ports: 
      - "27017:27017"
  web:
    build: .
    command: python3 src/series.py
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    depends_on:
      - db